### ISSUE TITLE
Incorrect images for spacers

### ISSUE THREAD

**Issue by devinberg** [FarmBot-Docs/farmbot-genesis#58]
On the [Assemble the Gantry Wheel Plates](https://genesis.farm.bot/v1.6/assembly/gantry/assemble-the-gantry-wheel-plates) ([source](https://github.com/FarmBot-Docs/farmbot-genesis/blob/main/v1.6/assembly/gantry/assemble-the-gantry-wheel-plates.md)) page, the hover images for `[[eccentric spacer(s)]]` are incorrect. All four instances show a standard spacer instead.

Similarly, on the [Spacer](https://genesis.farm.bot/v1.6/bom/fasteners-and-hardware/spacer) ([source](https://github.com/FarmBot-Docs/farmbot-genesis/blob/main/v1.6/bom/fasteners-and-hardware/spacer.md)) product information page, the first image shows eccentric spacers rather than standard spacers. This could be a point of confusion during assembly.

**Comment by roryaronson** [comment]
@devinberg thank you for pointing this out! I have just deployed an [update](https://github.com/FarmBot-Docs/farmbot-genesis/pull/59) to the documentation that fixes this issue. It should be live on the site within about 15 minutes. You may need to perform a hard refresh (control + shift + R) to ensure your browser purges it's cache.
