### ISSUE TITLE
Watering Nozzle images show the electrical connections the wrong way in Genesis ver 1.6 Documentation

### ISSUE THREAD

**Issue by Darksplat** [FarmBot-Docs/farmbot-genesis#91]
From step 2 onwards the picture showcasing the constructed water nozzle shows the electrical connections facing the opposite way of the directional arrow of water flow. All of step 1 pictures are correct but from step 2 it is going in the opposite direction causing confusion in which direction the pressure regulator should go and therefore which direction the water nozzle should be mounted.

Please fix the images so that all pictures match step 1 pictures in this regard

v1.6/assembly/tools/watering-nozzle.md

Cheers

**Comment by roryaronson** [comment]
Thank you for pointing this out. I have just updated the images to be consistent, and added an extra note pointing out that some manufacturing runs had the electrical terminals aligned with the water flow direction and others did not.
